# common configuration for ALL branches
image: Visual Studio 2026

before_build:
  - dotnet restore NumericsLab\NumericsLab.csproj

build:
  project: NumericsLab\NumericsLab.csproj

platform:
  - Any CPU

configuration:
  - Release

branches:
  only:
  - main

version: 0.0.1.7-{build}

artifacts:
  - path: '**\*.nupkg'

deploy:
  - provider: NuGet
    api_key:
      secure: ArGjpnCkHrBwrLEVpIHRIXsSvqpL1dRVcfFAiUYsSh2sbCiSRLFKuczedSM38uFJ
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      APPVEYOR_REPO_TAG: true
